//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy for percent search:.
        /// </summary>
        public static string AccuracyPercentSearchLabel {
            get {
                return ResourceManager.GetString("AccuracyPercentSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After changes.
        /// </summary>
        public static string AfterChanges {
            get {
                return ResourceManager.GetString("AfterChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha changed:.
        /// </summary>
        public static string AlphaChangedLabel {
            get {
                return ResourceManager.GetString("AlphaChangedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha:.
        /// </summary>
        public static string AlphaLabel {
            get {
                return ResourceManager.GetString("AlphaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string AnalysisButton {
            get {
                return ResourceManager.GetString("AnalysisButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data.
        /// </summary>
        public static string AnalysisDataSaveButton {
            get {
                return ResourceManager.GetString("AnalysisDataSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string CBasic {
            get {
                return ResourceManager.GetString("CBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string CDefault {
            get {
                return ResourceManager.GetString("CDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change C values:.
        /// </summary>
        public static string ChangeC {
            get {
                return ResourceManager.GetString("ChangeC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose accuracy (e):.
        /// </summary>
        public static string ChooseAccuracyLabel {
            get {
                return ResourceManager.GetString("ChooseAccuracyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonbasic.
        /// </summary>
        public static string CNonbasic {
            get {
                return ResourceManager.GetString("CNonbasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counted average percentage for your task.
        /// </summary>
        public static string CountedPercentageForTaskTextBlock {
            get {
                return ResourceManager.GetString("CountedPercentageForTaskTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:.
        /// </summary>
        public static string DistanceLabel {
            get {
                return ResourceManager.GetString("DistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose distribution:.
        /// </summary>
        public static string DistributionLabel {
            get {
                return ResourceManager.GetString("DistributionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The C values change parameter must be selected.
        /// </summary>
        public static string ExceptionCheckboxesC {
            get {
                return ResourceManager.GetString("ExceptionCheckboxesC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an accuracy.
        /// </summary>
        public static string ExceptionLabelAccuracyNOTChosen {
            get {
                return ResourceManager.GetString("ExceptionLabelAccuracyNOTChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delay must be numeric.
        /// </summary>
        public static string ExceptionLabelDelayNumeric {
            get {
                return ResourceManager.GetString("ExceptionLabelDelayNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delay must be positive.
        /// </summary>
        public static string ExceptionLabelDelayPositive {
            get {
                return ResourceManager.GetString("ExceptionLabelDelayPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deviation must be numeric.
        /// </summary>
        public static string ExceptionLabelDeviationNumeric {
            get {
                return ResourceManager.GetString("ExceptionLabelDeviationNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deviation must be positive.
        /// </summary>
        public static string ExceptionLabelDeviationPositive {
            get {
                return ResourceManager.GetString("ExceptionLabelDeviationPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distribution for a and b 
        ///is not chosen yet.
        /// </summary>
        public static string ExceptionLabelDistributionABNOTChosen {
            get {
                return ResourceManager.GetString("ExceptionLabelDistributionABNOTChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distribution for matrixes 
        ///is not chosen yet.
        /// </summary>
        public static string ExceptionLabelDistributionCNOTChosen {
            get {
                return ResourceManager.GetString("ExceptionLabelDistributionCNOTChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distribution for l 
        ///is not chosen yet.
        /// </summary>
        public static string ExceptionLabelDistributionLNOTChosen {
            get {
                return ResourceManager.GetString("ExceptionLabelDistributionLNOTChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File chosen successfully.
        /// </summary>
        public static string ExceptionLabelFileChosenSuccesslully {
            get {
                return ResourceManager.GetString("ExceptionLabelFileChosenSuccesslully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not chosen.
        /// </summary>
        public static string ExceptionLabelFileIsNOTChosen {
            get {
                return ResourceManager.GetString("ExceptionLabelFileIsNOTChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format of input file.
        /// </summary>
        public static string ExceptionLabelIncorrectFileFormat {
            get {
                return ResourceManager.GetString("ExceptionLabelIncorrectFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;n&apos; must be integer.
        /// </summary>
        public static string ExceptionLabelIntegerN {
            get {
                return ResourceManager.GetString("ExceptionLabelIntegerN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;R&apos; must be integer.
        /// </summary>
        public static string ExceptionLabelIntegerR {
            get {
                return ResourceManager.GetString("ExceptionLabelIntegerR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range of sizing.
        /// </summary>
        public static string ExceptionLabelInvalidRangeSizing {
            get {
                return ResourceManager.GetString("ExceptionLabelInvalidRangeSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough data for this task.
        /// </summary>
        public static string ExceptionLabelNOTEnoughData {
            get {
                return ResourceManager.GetString("ExceptionLabelNOTEnoughData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough data for this size of matrix (n) 
        ///and experts quantity (R).
        /// </summary>
        public static string ExceptionLabelNOTEnoughDataForParameters {
            get {
                return ResourceManager.GetString("ExceptionLabelNOTEnoughDataForParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range must consist of integers.
        /// </summary>
        public static string ExceptionLabelNRangeIntegers {
            get {
                return ResourceManager.GetString("ExceptionLabelNRangeIntegers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;n&apos; must be positive.
        /// </summary>
        public static string ExceptionLabelPositiveN {
            get {
                return ResourceManager.GetString("ExceptionLabelPositiveN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;R&apos; must be positive.
        /// </summary>
        public static string ExceptionLabelPositiveR {
            get {
                return ResourceManager.GetString("ExceptionLabelPositiveR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range C must consist of numbers.
        /// </summary>
        public static string ExceptionLabelRangeNumbers {
            get {
                return ResourceManager.GetString("ExceptionLabelRangeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range C must be positive.
        /// </summary>
        public static string ExceptionLabelRangePositive {
            get {
                return ResourceManager.GetString("ExceptionLabelRangePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range C must be in positive numbers.
        /// </summary>
        public static string ExceptionLabelRangeStartsInPositive {
            get {
                return ResourceManager.GetString("ExceptionLabelRangeStartsInPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range of quantities.
        /// </summary>
        public static string ExceptionLabelRInvalidQuatitySizing {
            get {
                return ResourceManager.GetString("ExceptionLabelRInvalidQuatitySizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range R must consist of numbers.
        /// </summary>
        public static string ExceptionLabelRRangeIntegers {
            get {
                return ResourceManager.GetString("ExceptionLabelRRangeIntegers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range R must be positive.
        /// </summary>
        public static string ExceptionLabelRRangePositive {
            get {
                return ResourceManager.GetString("ExceptionLabelRRangePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The step R must be integer.
        /// </summary>
        public static string ExceptionLabelRStepInteger {
            get {
                return ResourceManager.GetString("ExceptionLabelRStepInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The step R must be positive.
        /// </summary>
        public static string ExceptionLabelRStepPositive {
            get {
                return ResourceManager.GetString("ExceptionLabelRStepPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizes of matrixes must be positive.
        /// </summary>
        public static string ExceptionLabelSizesMatrixesPositive {
            get {
                return ResourceManager.GetString("ExceptionLabelSizesMatrixesPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The step C must be integer.
        /// </summary>
        public static string ExceptionLabelStepInteger {
            get {
                return ResourceManager.GetString("ExceptionLabelStepInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The step C must be positive.
        /// </summary>
        public static string ExceptionLabelStepPositive {
            get {
                return ResourceManager.GetString("ExceptionLabelStepPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponential.
        /// </summary>
        public static string Exponential {
            get {
                return ResourceManager.GetString("Exponential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percentage of change of input data is not acceptable. This means that the given compromise solution is not stable enough.
        /// </summary>
        public static string FailedPersistenceTestTextBlock {
            get {
                return ResourceManager.GetString("FailedPersistenceTestTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find percent.
        /// </summary>
        public static string FindPercentButton {
            get {
                return ResourceManager.GetString("FindPercentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator for vectors a and b:.
        /// </summary>
        public static string GeneratorABLabel {
            get {
                return ResourceManager.GetString("GeneratorABLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator for matrixes C:.
        /// </summary>
        public static string GeneratorCLabel {
            get {
                return ResourceManager.GetString("GeneratorCLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator for vector l:.
        /// </summary>
        public static string GeneratorLLabel {
            get {
                return ResourceManager.GetString("GeneratorLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string GraphPercentageLine {
            get {
                return ResourceManager.GetString("GraphPercentageLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of change by changing optimum.
        /// </summary>
        public static string GraphPercentageY {
            get {
                return ResourceManager.GetString("GraphPercentageY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of matrix.
        /// </summary>
        public static string GraphSizeOfMatrixX {
            get {
                return ResourceManager.GetString("GraphSizeOfMatrixX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of percentages from the base for given size of matrixes:.
        /// </summary>
        public static string ListOfPercentagesDBTextBlock {
            get {
                return ResourceManager.GetString("ListOfPercentagesDBTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research process support system for transport problem 
        ///under uncertainty.
        /// </summary>
        public static string MainTextBlock {
            get {
                return ResourceManager.GetString("MainTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrixes C:.
        /// </summary>
        public static string MatrixesCLabel {
            get {
                return ResourceManager.GetString("MatrixesCLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrixes.
        /// </summary>
        public static string Matrixs {
            get {
                return ResourceManager.GetString("Matrixs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal Value:.
        /// </summary>
        public static string OptimalValueLabel {
            get {
                return ResourceManager.GetString("OptimalValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal X:.
        /// </summary>
        public static string OptimalXLabel {
            get {
                return ResourceManager.GetString("OptimalXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay mean:.
        /// </summary>
        public static string ParametersExpLabel {
            get {
                return ResourceManager.GetString("ParametersExpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay mean and deviation:.
        /// </summary>
        public static string ParametersNormalLabel {
            get {
                return ResourceManager.GetString("ParametersNormalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range for generator:.
        /// </summary>
        public static string ParametersUniformLabel {
            get {
                return ResourceManager.GetString("ParametersUniformLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average percentage based on data after performed experiments.
        /// </summary>
        public static string PercentageFromDBTextBlock {
            get {
                return ResourceManager.GetString("PercentageFromDBTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistence Test.
        /// </summary>
        public static string PersistenceButton {
            get {
                return ResourceManager.GetString("PersistenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file with your task and solution for test and accuracy for percentage search.
        /// </summary>
        public static string PersistenceInputTextBlock {
            get {
                return ResourceManager.GetString("PersistenceInputTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string PersistenceSelectFileButton {
            get {
                return ResourceManager.GetString("PersistenceSelectFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on .
        /// </summary>
        public static string ProcessingSize {
            get {
                return ResourceManager.GetString("ProcessingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment done!.
        /// </summary>
        public static string ProgressTextBlockCompleted {
            get {
                return ResourceManager.GetString("ProgressTextBlockCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of cost matrixes (R):.
        /// </summary>
        public static string QuantityOfMatrixesLabel {
            get {
                return ResourceManager.GetString("QuantityOfMatrixesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range of changing quantity of matrix C:.
        /// </summary>
        public static string RangeChangingQuantityMatrixLabel {
            get {
                return ResourceManager.GetString("RangeChangingQuantityMatrixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range of changing size of matrix C:.
        /// </summary>
        public static string RangeChangingSizeMatrixLabel {
            get {
                return ResourceManager.GetString("RangeChangingSizeMatrixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R range:.
        /// </summary>
        public static string RangeR {
            get {
                return ResourceManager.GetString("RangeR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string RunButton {
            get {
                return ResourceManager.GetString("RunButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save graph.
        /// </summary>
        public static string SaveGraphButton {
            get {
                return ResourceManager.GetString("SaveGraphButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save input data.
        /// </summary>
        public static string SaveInputDataButton {
            get {
                return ResourceManager.GetString("SaveInputDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save result.
        /// </summary>
        public static string SaveResultButton {
            get {
                return ResourceManager.GetString("SaveResultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of matrix.
        /// </summary>
        public static string SizeOfMatrixFile {
            get {
                return ResourceManager.GetString("SizeOfMatrixFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of matrix (n):.
        /// </summary>
        public static string SizeOfMatrixLabel {
            get {
                return ResourceManager.GetString("SizeOfMatrixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions X:.
        /// </summary>
        public static string SolutionsXLabel {
            get {
                return ResourceManager.GetString("SolutionsXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solver.
        /// </summary>
        public static string SolverButton {
            get {
                return ResourceManager.GetString("SolverButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From file.
        /// </summary>
        public static string SolverFromFileButton {
            get {
                return ResourceManager.GetString("SolverFromFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a type of input.
        /// </summary>
        public static string SolverInputLabel {
            get {
                return ResourceManager.GetString("SolverInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string SolverRandomButton {
            get {
                return ResourceManager.GetString("SolverRandomButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run from file.
        /// </summary>
        public static string SolverRunFromFileButton {
            get {
                return ResourceManager.GetString("SolverRunFromFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step in changing size of matrix C:.
        /// </summary>
        public static string StepChangingSizeMatrixLabel {
            get {
                return ResourceManager.GetString("StepChangingSizeMatrixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step for R change:.
        /// </summary>
        public static string StepR {
            get {
                return ResourceManager.GetString("StepR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percentage of change of input data is acceptable for the given parameters. The compromise solution is stable enough.
        /// </summary>
        public static string SuccesfulPersistenceTestTextBlock {
            get {
                return ResourceManager.GetString("SuccesfulPersistenceTestTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform.
        /// </summary>
        public static string Uniform {
            get {
                return ResourceManager.GetString("Uniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables: .
        /// </summary>
        public static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
    }
}
